### ISSUE TITLE
compile and default NNUE

### ISSUE THREAD

**Issue by tissatussa** [Quanticade/Quanticade#36]
i wonder about the NNUE option :

```
option name Use NNUE type check default true
option name EvalFile type string default nn.nnue
```

i guess the `nn.nnue` (2.3 Mb) is embedded in the binary (2.4 Mb), so how to interpret the above two options ? Can the value of `EvalFile` be empty while `NNUE` is true ? Should `nn.nnue` be placed in the same folder as the binary when running it ? Can another NN file be used / compiled into ? Which format is used, some own format ?

i successfully compiled the newest source code (PR 35) like this :

```
make CC=gcc-13
```

the Makefile shows options for `avx2` and `bmi2`, are they included automatically ? My notebook supports those.

what about `PGO` ? Do i have to supply an argument for the `make` command ?

you could expand the README to tackle these questions.

**Comment by Haxk20** [comment]
> i wonder about the NNUE option :
> 
> ```
> option name Use NNUE type check default true
> option name EvalFile type string default nn.nnue
> ```
> 
> i guess the `nn.nnue` (2.3 Mb) is embedded in the binary (2.4 Mb), so how to interpret the above two options ? Can the value of `EvalFile` be empty while `NNUE` is true ? Should `nn.nnue` be placed in the same folder as the binary when running it ? Can another NN file be used / compiled into ? Which format is used, some own format ?

Yes, nn.nnue is compiled into the binary.
The use nnue option is rather simple. It switches between HCE and NNUE evaluation.
EvalFile is simply to change the NNUE network at runtime. For example if engine was compiled with some network and you want to use a different network.

Format is (768 -> 1536)x2 -> 1. Prefixed is an string for verifying the validity of the network. Quanticade will not load the network if it doesn't find this string. (Check source code for the string)

The nn.nnue doesn't have to be in the same folder as the binary but honestly speaking it is better to have it in the same folder in case loading from binary is broken (when compiling with clang on windows)
> 
> i successfully compiled the newest source code (PR 35) like this :
> 
> ```
> make CC=gcc-13
> ```
> 
> the Makefile shows options for `avx2` and `bmi2`, are they included automatically ? My notebook supports those.
The makefile checks for CPU capabilities and enables and tunes for your specific CPU model on its own. This is done automatically.
> 
> what about `PGO` ? Do i have to supply an argument for the `make` command ?
If you want to use PGO (there is quite literally no performance boost) simply add pgo argument to make command.
> 
> you could expand the README to tackle these questions.
> 

The README already explains the specified UCI options.

I will make sure to explain how to compile it and make arguments.

**Comment by tissatussa** [comment]
> (PGO) there is quite literally no performance boost

why not ? recently i experimented with those 'profiling' techniques, producing `.gcda` files and in a next step use those to 'tune' the engine / code ? Doesn't compiling Stockfish also use this method ? While compiling SF based engines i often see some FENs being evaluated .. is this PGO ? Or am i wrong here ?

**Comment by Haxk20** [comment]
> > (PGO) there is quite literally no performance boost
> 
> why not ? recently i experimented with those 'profiling' techniques, producing `.gcda` files and in a next step use those to 'tune' the engine / code ? Doesn't compiling Stockfish also use this method ? While compiling SF based engines i often see some FENs being evaluated .. is this PGO ? Or am i wrong here ?

Because Quanticade is not Stockfish. Some engines simply do not gain speed from PGO. This is the case for Quanticade. Sadly.... Would be nice to have free elo LOL

**Comment by Haxk20** [comment]
I will now be closing this issue
