### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by SzotsGabor** [Quanticade/Quanticade#51]
This is from CCRL point of view.

Aurora is already on the 40/15 list. Now this Quanticade, if tested, will appear as Quanticade. Same engine, different entries on the list. Yet some more versions and the list will be polluted by several engines seeemingly different but in fact belonging in the same family. That is not particularly desirable and it might induce CCRL members to refrain from testing the engine. I don't think either you or we would want that.

Gabor Szots, CCRL

**Comment by Haxk20** [comment]
What would be the desires naming then ? Just Quanticade 0.8 ?

**Comment by AlexBrunetti** [comment]
> This is from CCRL point of view.
> 
> Aurora is already on the 40/15 list. Now this Quanticade, if tested, will appear as Quanticade. Same engine, different entries on the list. Yet some more versions and the list will be polluted by several engines seeemingly different but in fact belonging in the same family. That is not particularly desirable and it might induce CCRL members to refrain from testing the engine. I don't think either you or we would want that.
> 
> Gabor Szots, CCRL

Hey Gabor!
Are you sure that the 40/15 Aurora you are referring to is the same engine?

Alex

**Comment by Haxk20** [comment]
> > This is from CCRL point of view.
> > Aurora is already on the 40/15 list. Now this Quanticade, if tested, will appear as Quanticade. Same engine, different entries on the list. Yet some more versions and the list will be polluted by several engines seeemingly different but in fact belonging in the same family. That is not particularly desirable and it might induce CCRL members to refrain from testing the engine. I don't think either you or we would want that.
> > Gabor Szots, CCRL
> 
> Hey Gabor! Are you sure that the 40/15 Aurora you are referring to is the same engine?
I see Aurora 1.0.0 on the list. Aurora is NOT Quanticade.

Quanticade simply uses a naming scheme of EngineName VersionName VersionNumber
> 
> Alex

**Comment by SzotsGabor** [comment]
> > This is from CCRL point of view.
> > Aurora is already on the 40/15 list. Now this Quanticade, if tested, will appear as Quanticade. Same engine, different entries on the list. Yet some more versions and the list will be polluted by several engines seeemingly different but in fact belonging in the same family. That is not particularly desirable and it might induce CCRL members to refrain from testing the engine. I don't think either you or we would want that.
> > Gabor Szots, CCRL
> 
> Hey Gabor! Are you sure that the 40/15 Aurora you are referring to is the same engine?
> 
> Alex

Hi Alex,

No, I'm not. In fact now I think they are different engines.

**Comment by SzotsGabor** [comment]
It seems I have mistaken the two engines and created a mess. Apologies.

I'm going to make amends by selecting Quanticade for my next test tournament for the CCRL blitz list.

**Comment by Haxk20** [comment]
Since this was a mistake i will be closing this issue.

Also thank you Gabor :)
