### ISSUE TITLE
Quanticade 0.9 Error loading the net

### ISSUE THREAD

**Issue by toni-chess** [Quanticade/Quanticade#76]
hello!
running from Command prompt...
We read: 1579060 but the expected is 1607708
Error loading the net, aborting
.................................
I'm so sorry!
this error ocur becouse of the old net was in same directoy with Quanticade 0.9.

**Comment by Haxk20** [comment]
I was about to ask if you didn't have the old net in the same folder :)

Glad this is sorted :)
