### ISSUE TITLE
nn naming

### ISSUE THREAD

**Issue by SzotsGabor** [Quanticade/Quanticade#80]
Hi Martin,

May I ask you to differentiate between nn's by their name? As it is, I have to place different Quanticade versions in different folders because their nn is different but its name is the same. I'd rather not do that if possible.

Gabor Szots
CCRL testing group

**Comment by Haxk20** [comment]
Yea i can do that in the next release

**Comment by Haxk20** [comment]
Forgot to close this when I replied last time to this.
